import Head from 'next/head';

import Image from "next/image";
import { Banner } from '@/components/banner';
import { Card } from '@/components/card';
import coffeeStores from '../data/coffee-stores.json';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button")
  }

  return (
    <div className={styles.conatiner}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
        <Image className={styles.heroImage} src="/static/hero-image.png" width={700} height={400}></Image>
        <div className={styles.cardLayout}>
          {coffeeStores.map(coffeeStore => {
            return (
              <Card name={coffeeStore.name} imageUrl={coffeeStore.imgUrl} href="/coffee-store/darkhorse-coffee" className={styles.card} />
            )
          })}
        </div>
      </main>
    </div>
  )
}
